E_commerce/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  root 'products#index'
  get "products" , to: "products#index"
  get "products/new", to: "products#new"
  get "products/:id", to: "products#show" # , as: :product
  resources :products, :orders
  post "products", to: "products#create"
  get "products/:id/edit", to: "products#edit", as: :product_edit
  patch "products/:id", to: "products#update"
  delete "products/:id", to: "products#destroy"
  
  get "products/showit/:id" , to: "products#showit"
  get "orders/new/:id" , to: "orders#new"
  
  get "orders/new", to: "orders#new"
  post "orders", to: "orders#create"

  get "orders" , to: "orders#index"
  
  get "add_quantity" , to: "products#add_quantity"

  get "orders/showit/:id" , to: "orders#showit"
  

end

E_commerce/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

E_commerce/app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    belongs_to :product
end

E_commerce/app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
 #   belongs_to :order
    has_many :orders, dependent: :destroy
end

E_commerce/app/models/user.rb
class User < ApplicationRecord
  has_many :products
  has_many :orders

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

E_commerce/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

E_commerce/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    
    before_action :authenticate_user!

    def index
        @orders = Order.where(user_id: current_user.id)
    end


    def show
        @order = Order.find(params[:id])
        @product = @order.product
    end

  def new
    @product = Product.find(params[:product_id])
    @order = Order.new

  end
  
  def create 
    product = Product.find(params[:order][:product_id])
    @order = Order.new(order_params) 
    @order.user_id = current_user.id
    add_quantity
    @order.save
    redirect_to orders_path
  end
  
  
  def destroy
    Order.find(params[:id]).destroy
    redirect_to orders_path
  end

 
  def update
    order = Order.find(params[:id])
    order.update(order_params)
    redirect_to orders_path
end


    private
    def order_params
        params.require(:order).permit(:quantity, :user_id , :product_id )
    end


    def add_quantity
        product = Product.find(params[:order][:product_id])
        @product = @order.product  
        @product.stock -= @order.quantity
        @product.save
      end


end

E_commerce/app/controllers/products_controller.rb
class ProductsController < ApplicationController

     before_action :authenticate_user!

    def index
        @products = Product.all
        # @products = Product.where(user_id: current_user.id)
    end

    def new
      @product = Product.new
    end

    def create  
        puts params          
        @product = Product.new(product_params) 
        @product.user_id = current_user.id
        @product.save
        redirect_to @product 
    end

    
    def update
        product = Product.find(params[:id])
        product.update(params.require(:product).permit(:name, :price, :img, :description, :user_id, :stock,  :order_ids => [] ))
        redirect_to product 
    end

    

    def edit
        @product = Product.find(params[:id])
    end


    def destroy
        Product.find(params[:id]).destroy
        redirect_to products_path
    end

    
    def show
        @product = Product.find(params[:id])
        # This code below has a quick demo of how to form a json object with nested ingredients on a recipe.
        #render json: @product, include: :orders
    end

    def showit
        @products = Product.where(user_id: current_user.id)
    end    


   

    private
    def product_params
        params.require(:product).permit(:name, :price, :img, :description, :user_id, :stock,  :order_ids => [] )
    end

end

E_commerce/app/helpers/application_helper.rb
module ApplicationHelper
end

E_commerce/app/helpers/products_helper.rb
module ProductsHelper
end

E_commerce/app/views/layouts/_nav.html.erb
<p class="navbar-text pull-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
  </p>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  

E_commerce/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>ECommerce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/nav' %>

    <%= yield %>
  </body>
</html>

E_commerce/app/views/orders/index.html.erb
<h1>All Your Orders</h1>
<div class='divfo'>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">PRODUCT Id </th>
      <th scope="col">Quantity</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.product_id %></td>
        <td><%= order.quantity %></td>
        <td>
        <div class="btn btn-danger"  role="group" aria-label="Basic example">
        <%= link_to 'Show', order , :class => "btn btn-danger" %>  |
        <%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-danger" %> 
        </div></td>
      </tr>
    <% end %>
  </tbody>
</table>


</div>
<br>

<%= link_to 'Back to product path', products_path, :class => "btn btn-danger" %>

E_commerce/app/views/orders/new.html.erb
<h1>New Order</h1>
<br>




<%= form_for(@order) do |f| %>
   
    <%= f.hidden_field :product_id, :value => @product.id %>
      <p> Quantity </p>
      <%= f.select(:quantity, options_for_select(1..@product.stock)) %>
      <br>
      <br>
      <div class="btn btn-danger"  role="group" aria-label="Basic example">
        <%=  f.submit 'Submit', :class => "btn btn-danger" %>  |
        <%= link_to 'Back', orders_path, :class => "btn btn-danger" %> 
        </div>

     
    <% end %>

   

E_commerce/app/views/orders/show.html.erb
<h3 class="show"> product name: </h3> 
<h3 class="show2"> <%= @product.name %> </h3>

<h3 class="show"> Price: </h3> 
<h3 class="show2"> <%= @product.price %> SR</h3>

<%= image_tag(@product.img , size: "200x250", alt: "product Image") %>

<h3 class="show"> Description: </h3> 
<h3 class="show2"> <%=@product.description %> </h3>

<h3 class="show"> Quantity: </h3> 
<h3 class="show2"> <%=@order.quantity %> </h3>


<br>
<%= link_to 'Back to orders', orders_path , :class => "btn btn-danger" %>
<br>

E_commerce/app/views/products/edit.html.erb
<h1>Edit <%= @product.name %></h1>
<%= image_tag(@product.img , size: "300x350", alt: "product Image") %>
<div class='divfo'>
<%= form_for @product do |f| %>
    <div class="form-group">
      <%= f.label :name, "Product Name" %>
  <div class="col-sm-10">
      <%= f.text_field :name %>
    </div></div>
  <div class="form-group">
    <%= f.label :price, "Price" %>
  <div class="col-sm-10">
    <%= f.text_field :price %>
  </div></div>

  <div class="form-group">
    <%= f.label :img, "img" %>
    <div class="col-sm-10">   
    <%= f.text_field :img %>
    </div></div>

    <div class="form-group">
    <%= f.label :description, "description" %>
    <div class="col-sm-10">  
    <%= f.text_field :description %>
    </div></div>

    <div class="form-group">
    <%= f.label :stock, "stock" %>
    <div class="col-sm-10">  
    <%= f.text_field :stock %>
    </div></div>
   
<div class="btn btn-danger"  role="group" aria-label="Basic example">
<%= f.submit "Submit", :class => "btn btn-danger" %> |
<%= link_to 'Show', @product ,:class => "btn btn-danger"%> |
<%= link_to 'Back', products_path ,:class => "btn btn-danger"%>
</div>

  <% end %>
 
</div>

E_commerce/app/views/products/index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">  Name  </th>
      <th scope="col">  Price  </th>
      <th scope="col">  Img  </th>
      <th scope="col">  Description  </th>
      <th scope="col">  Stock  </th>
      <th scope="col">  Show  </th>

    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr> 
        <td><%= product.name %></td>
        <td><%= product.price %> SR</td>
        <td><%= image_tag(product.img , size: "150x180", alt: "product Image") %></td>
        <td><%= product.description %></td>
        <td><%= product.stock %></td>
        <td><%= link_to 'Show', product ,  :class => "btn btn-danger"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="btn btn-danger"  role="group" aria-label="Basic example">
<%= link_to 'Add a new product', new_product_path , :class => "btn btn-danger" %> |
<%= link_to 'Show your products', "products/showit/:id", :class => "btn btn-danger" %>  |
<%= link_to 'Show your Orders', "orders" , :class => "btn btn-danger" %> 
</div>

E_commerce/app/views/products/new.html.erb
<div class='divfo'>
<%= form_for(@product) do |f| %>
  <div class="form-group">
      <%= f.label :name, "Product Name" %>
  <div class="col-sm-10">
      <%= f.text_field :name %>
    </div></div>
  <div class="form-group">
    <%= f.label :price, "Price" %>
  <div class="col-sm-10">
    <%= f.text_field :price %>
  </div></div>

  <div class="form-group">
    <%= f.label :img, "img" %>
    <div class="col-sm-10">   
    <%= f.text_field :img %>
    </div></div>

    <div class="form-group">
    <%= f.label :description, "description" %>
    <div class="col-sm-10">  
    <%= f.text_field :description %>
    </div></div>

    <div class="form-group">
    <%= f.label :stock, "stock" %>
    <div class="col-sm-10">  
    <%= f.text_field :stock %>
    </div></div>

  
    <div class="btn btn-danger"  role="group" aria-label="Basic example">
    <%= f.submit 'Submit', :class => "btn btn-danger" %>  |
    <%= link_to 'Back', products_path, :class => "btn btn-danger" %> 
    </div>

  <% end %>
  
  
</div>

E_commerce/app/views/products/show.html.erb
<h3 class="show"> product name: </h3> 
<h3 class="show2"> <%= @product.name %> </h3>

<h3 class="show">Price: </h3>
<h3 class="show2"><%= @product.price %> SR</h3>

<h4><%= image_tag(@product.img , size: "300x350", alt: "product Image") %></h4>
<h3 class="show">Description: </h3>
<h3 class="show2"><%= @product.description %></h3>
<h3 class="show">Stock: </h3>
<h3 class="show2"><%= @product.stock%></h3>



<div class="btn btn-danger"  role="group" aria-label="Basic example">
<%= link_to 'Add to cart', new_order_path(:product_id => @product.id) , :class => "btn btn-danger" %>  |
<%= link_to 'Back', products_path, :class => "btn btn-danger" %> 
</div>

E_commerce/app/views/products/showit.html.erb
<h1><%= current_user.email %>'s Products</h1>


<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">  Name  </th>
      <th scope="col">  Price  </th>
      <th scope="col">  Img  </th>
      <th scope="col">  Description  </th>
      <th scope="col">  Stock  </th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %> SR</td>
        <td><%= image_tag(product.img , size: "100x100", alt: "product Image") %></td>
        <td><%= product.description %></td>
        <td><%= product.stock %></td>
        <td>
        <div class="btn btn-danger"  role="group" aria-label="Basic example">
        <%= link_to 'Edit', edit_product_path(product) , :class => "btn btn-danger" %>  |
        <%= link_to 'Destroy', product, method: :delete, data: {  confirm: 'Are you sure?'} , :class => "btn btn-danger" %> 
        </div> </td>
      </tr>
   <% end %>
  </tbody>
</table>

<br>

<div class="btn btn-danger"  role="group" aria-label="Basic example">
<%= link_to 'New product', new_product_path , :class => "btn btn-danger" %>  |
<%= link_to 'Back', products_path, :class => "btn btn-danger" %> 
</div>